# Generated by Django 5.0.3 on 2024-08-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudRiskScoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskscore',
            name='transactionid',
            field=models.CharField(default='00000000', max_length=100, unique=True),
        ),
    ]
